name: Documentation

on: [pull_request, workflow_dispatch]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'docs/requirements.txt'
    - run: python -m pip install -r docs/requirements.txt
    - run: python -m pip install .
    - run: python -m sphinx -W -b html -d docs/build/doctrees docs/source docs/build/html
